export const locations = [
  { slug: "fm-chesterfield", city: "Chesterfield", region: "Derbyshire", subheading: "EntireFM delivers bespoke FM services across Chesterfield and Derbyshire — supporting commercial, industrial, and residential clients from our East Midlands regional base.", intro: "Chesterfield's mix of light industrial, retail, and residential estates requires robust management. With a growing commercial quarter and close links to the Sheffield corridor M1, many logistics and manufacturing businesses here require strict, compliance-led hard FM." },
  { slug: "fm-birmingham", city: "Birmingham", region: "West Midlands", subheading: "From Birmingham's city centre commercial core to the wider West Midlands industrial belt — EntireFM provides the FM expertise your operation demands.", intro: "As the UK's second city, Birmingham holds a huge commercial and retail estate, alongside a significant residential property management sector. We support the major logistics and manufacturing belt around the M6/M42 corridor, tackling the post-HS2 development increasing FM demand." },
  { slug: "fm-sheffield", city: "Sheffield", region: "South Yorkshire", subheading: "EntireFM supports Sheffield businesses and property managers with comprehensive FM services — rooted in the city's industrial heritage, built for its modern commercial landscape.", intro: "Sheffield is where industrial heritage meets a creative digital economy. We manage large university estates, a growing commercial property market, and significant manufacturing and advanced engineering sectors requiring specialist hard FM." },
  { slug: "fm-london", city: "London", region: "Greater London", subheading: "EntireFM delivers facilities management for London's demanding commercial, residential, and corporate property market — responsive, compliant, and built for the capital's pace.", intro: "London's corporate offices, high-rise residential properties, retail hubs, and hospitality venues operate in a stringent compliance environment. Multi-site estate management is common, and 24/7 operations are the norm, not the exception." },
  { slug: "fm-leeds", city: "Leeds", region: "West Yorkshire", subheading: "Comprehensive FM services for Leeds and West Yorkshire — supporting the region's growing commercial, retail, and residential property market.", intro: "Leeds is one of the UK's fastest-growing commercial cities with a strong financial and professional services sector. The growing build-to-rent residential market and major retail estates require precise, dedicated FM support." },
  { slug: "facilities-management-in-the-midlands", city: "The Midlands", region: "The Midlands", subheading: "EntireFM's Midlands FM operation serves clients across the East and West Midlands — from Birmingham to Derby, Leicester to Coventry.", intro: "The Midlands operates as the logistics hub of the UK. From major manufacturing belts to diverse commercial, retail, industrial, and residential sites, EntireFM manages the region's complex FM requirements entirely." },
  { slug: "facilities-management-manchester", city: "Manchester", region: "Greater Manchester", subheading: "Facilities management for Manchester's commercial, industrial, and residential property market — delivered by EntireFM with 24/7 support and nationwide backing.", intro: "A major northern commercial hub, Manchester's MediaCityUK and Salford developments drive demand. We manage a massive retail and hospitality estate alongside a huge residential build-to-rent market and the strong logistics belt around the M60/M62." },
  { slug: "fm-nottingham", city: "Nottingham", region: "East Midlands", subheading: "EntireFM provides bespoke FM services across Nottingham and the East Midlands — hard FM, PPM, cleaning, and reactive maintenance for commercial and residential clients.", intro: "Nottingham features a mix of retail, immense education campuses (including two major universities), healthcare, and commercial office markets. The light industrial and growing residential property sectors rely heavily on integrated TFM." },
  { slug: "fm-derby", city: "Derby", region: "East Midlands", subheading: "FM services for Derby's manufacturing, logistics, and commercial property market — delivered by EntireFM from our East Midlands base.", intro: "Derby is synonymous with the Rolls-Royce aerospace hub and wider advanced manufacturing. We support significant logistics and warehousing here. The commercial property market is growing rapidly alongside massive infrastructure investment." },
  { slug: "fm-lincoln", city: "Lincoln", region: "Lincolnshire", subheading: "Expert facilities management in Lincoln — supporting the historic city's commercial, retail, and manufacturing sectors with reliable FM delivery.", intro: "Lincoln's commercial landscape is a unique blend of heritage and modern industry. From the historic retail core to the modern manufacturing hubs and growing university campus, EntireFM delivers the compliance-led FM support required to maintain operational excellence." },
  { slug: "fm-liverpool", city: "Liverpool", region: "Merseyside", subheading: "Bespoke FM services for Liverpool and Merseyside — delivering hard FM, PPM, and reactive maintenance for maritime, logistics, and commercial estates.", intro: "Liverpool's maritime heritage and status as a major UK port drive a massive logistics and industrial sector. Combined with a vibrant commercial core and significant retail estates like Liverpool ONE, the city requires a sophisticated, multi-trade FM approach." },
  { slug: "facilities-management-bradford", city: "Bradford", region: "West Yorkshire", subheading: "Professional facilities management in Bradford — supporting the region's manufacturing, retail, and digital economy with expert FM support.", intro: "Bradford is a major contributor to the northern economy, with a strong manufacturing base and a rapidly growing digital sector. We provide comprehensive FM services to manage the city's diverse property portfolio, from historic industrial sites to modern commercial offices." },
  { slug: "facilities-management-in-telford", city: "Telford", region: "Shropshire", subheading: "Reliable FM services in Telford — supporting the town's significant manufacturing and logistics hub with compliance-focused FM delivery.", intro: "As a major manufacturing and distribution hub in the West Midlands/Shropshire corridor, Telford's business parks and industrial estates require high-quality, reliable facilities management. EntireFM delivers the hard and soft FM services needed to keep these critical operations running 24/7." }
];

export function getLocationBySlug(slug: string) {
    return locations.find(loc => loc.slug === slug);
}
