export const sectors = [
  { slug: "hotel-facilities-management", name: "Hotel", strapline: "Guest Experience Starts with a Well-Managed Building", challenges: "There is zero tolerance for HVAC and heating failures in hospitality. Guest-facing system uptime is paramount. Food safety compliance, 24/7 operation with no downtime windows, and maintaining invisible but flawless hard FM behind the scenes are the challenges hotels face daily.", priorityServices: ["PPM (HVAC & Boilers)", "24/7 Reactive Helpdesk", "Fire Safety Compliance", "Building Fabric Maintenance"] },
  { slug: "residential-facilities-management", name: "Residential", strapline: "Safe, Comfortable, and Well-Maintained Homes for Every Resident", challenges: "Resident satisfaction dictates success. Maintaining communal area upkeep, rigid compliance for HMOs and managed blocks/build-to-rent, responsive reactive maintenance, and on-site caretaking form the bedrock of excellent residential property management.", priorityServices: ["Caretaking & Soft FM", "Grounds Maintenance", "Hard FM (Communal M&E, Lifts)", "Reactive Helpdesk"] },
  { slug: "commercial-facilities-management", name: "Commercial", strapline: "Workplace FM That Enhances Productivity and Protects Your People", challenges: "Modern office occupiers have soaring expectations. Multi-tenant compliance, stringent energy efficiency targets, spotless workspace cleanliness, and secure access control are non-negotiable for Category A commercial estates.", priorityServices: ["Hard FM & PPM", "Commercial Cleaning", "Security & Access", "24/7 Helpdesk & Building Fabric"] },
  { slug: "arena-facilities-management", name: "Arena / Stadium", strapline: "Event-Ready, Every Time", challenges: "High footfall environments demand resilience. Rapid turnaround between major events, critical system uptime during operations, uncompromising statutory compliance, and flawless external audience areas define stadium FM.", priorityServices: ["Hard FM & PPM", "Industrial Cleaning", "Event Security & Grounds", "Reactive Helpdesk"] },
  { slug: "industrial-facilities-management", name: "Industrial", strapline: "Keeping Complex Operations Running Without Interruption", challenges: "Heavy-duty manufacturing environments require specialist cleaning and profound compliance for industrial plant machinery. Drone inspections for massive structures and expansive external yard maintenance are daily necessities.", priorityServices: ["Industrial Cleaning (Alkota/Oertzen)", "Drone Inspection", "Hard FM & Statutory Compliance", "Grounds & Yard Maintenance"] },
  { slug: "retail-facilities-management", name: "Retail", strapline: "Consistent Standards Across Every Site, Every Day", challenges: "Retail demands multi-site management with flawless brand consistency. Customer-facing cleanliness, vital out-of-hours maintenance, and consolidated compliance across a national portfolio dictate the strategy.", priorityServices: ["National PPM Schedules", "Reactive Helpdesk", "Commercial Cleaning", "Multi-Site Reporting"] },
  { slug: "healthcare-facilities-management", name: "Healthcare", strapline: "Compliance and Cleanliness Where It Matters Most", challenges: "CQC compliance and profound infection control are critical. Stringent cleaning standards intersect with statutory maintenance for life-saving critical systems and rigorous water safety (Legionella) management.", priorityServices: ["PPM & Statutory Maintenance", "Water Safety (Legionella/L8)", "Specialist Clinical Cleaning", "24/7 Reactive Helpdesk"] },
  { slug: "education-facilities-management", name: "Education", strapline: "Safe Learning Environments, Expertly Maintained", challenges: "Safeguarding compliance is paramount. Managing massive estates with restricted seasonal maintenance windows (holidays) requires military precision. HVAC comfort in classrooms and vast grounds maintenance are daily priorities.", priorityServices: ["PPM & Hard FM", "Grounds Maintenance", "Compliance Documentation", "Soft FM & Cleaning"] },
  { slug: "landmark-facilities-management", name: "Landmark & Heritage", strapline: "Preserving the Past, Managing the Future", challenges: "Heritage buildings require delicate, expert-led hard FM. Managing iconic structures involves balancing modern compliance (fire, electrical, water) with strict conservation guidelines and high-profile public access.", priorityServices: ["Specialist Building Fabric", "Heritage-Sensitive M&E", "Compliance Auditing", "24/7 Security & Access"] },
  { slug: "warehouse-facilities-management", name: "Warehouse & Logistics", strapline: "Uptime is Revenue in Modern Logistics", challenges: "Logistics hubs never sleep. Maintaining loading bay safety, fire suppression systems for high-rack storage, and expansive floor cleanliness are non-negotiable for 24/7 warehouse operations.", priorityServices: ["Loading Bay Maintenance", "Fire Suppression (High-Rack)", "Industrial Floor Cleaning", "Critical Power (UPS/Gen)"] },
  { slug: "service-station-fm", name: "Service Station", strapline: "24/7 Support for the UK's Transport Network", challenges: "Motorway services are ultra-high footfall environments. Maintaining 24/7 toilet hygiene, fuel-safe drainage, and reliable food-court HVAC is critical for passenger satisfaction and safety.", priorityServices: ["24/7 Reactive Helpdesk", "Fuel-Safe Drainage", "Commercial Cleaning", "HVAC & Refrigeration"] }
];

export function getSectorBySlug(slug: string) {
    return sectors.find(sec => sec.slug === slug);
}
