project_id = "iaevqfmiwadbrezmpoyd"

[functions.submit-contact]
verify_jwt = false

[functions.submit-proposal]
verify_jwt = false

[functions.submit-supplier-application]
verify_jwt = false

[functions.smart-search]
verify_jwt = false

[functions.gsc-api]
verify_jwt = false

[functions.gsc-alert-checker]
verify_jwt = false

[functions.ping-sitemap]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.submit-helpdesk-job]
verify_jwt = false
