import { MetadataRoute } from 'next';
import { caseStudies } from '@/lib/caseStudies';
import { resources } from '@/lib/resources';
import { episodes } from '@/lib/buildingWalk';
import { academyCourses } from '@/lib/academy';
import { partnerTypes } from '@/lib/partners';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://www.entirefm.com';

  const staticRoutePaths = [
    '/',
    '/about',
    '/academy',
    '/arena-facilities-management',
    '/awards',
    '/blog',
    '/building-walk',
    '/careers',
    '/case-studies',
    '/commercial-facilities-management',
    '/compare',
    '/compare/entirefm-vs-call-out-only',
    '/compare/entirefm-vs-cbre',
    '/compare/entirefm-vs-freelance',
    '/compare/entirefm-vs-in-house',
    '/compare/entirefm-vs-jll',
    '/compare/entirefm-vs-mitie',
    '/compare/entirefm-vs-sodexo',
    '/compliance-pack',
    '/compliance-risk-diagnostic',
    '/contact',
    '/coverage',
    '/education-facilities-management',
    '/entirecafm',
    '/esg',
    '/facilities-management-birmingham',
    '/facilities-management-chesterfield',
    '/facilities-management-in-the-midlands',
    '/fm-derby',
    '/fm-insights',
    '/fm-insights/future-of-fm',
    '/fm-intelligence',
    '/fm-leeds',
    '/fm-london',
    '/fm-manchester',
    '/fm-market-report',
    '/fm-nottingham',
    '/fm-operations',
    '/fm-sheffield',
    '/health-safety',
    '/healthcare-facilities-management',
    '/hotel-facilities-management',
    '/industrial-facilities-management',
    '/innovation',
    '/integrations',
    '/leadership',
    '/link-health',
    '/locations',
    '/marketplace',
    '/partners',
    '/partnerships',
    '/request-proposal',
    '/residential-facilities-management',
    '/resources',
    '/resources/compliance-calendar',
    '/resources/document-vault',
    '/retail-facilities-management',
    '/search',
    '/sectors',
    '/sectors/airports',
    '/sectors/aviation-travel-hub',
    '/sectors/education',
    '/sectors/healthcare-public',
    '/sectors/hospitality-leisure',
    '/sectors/hotels-leisure',
    '/sectors/industrial-logistics',
    '/sectors/industrial-logistics-hub',
    '/sectors/logistics-parks',
    '/sectors/offices',
    '/sectors/offices-corporate',
    '/sectors/pbsa-hub',
    '/sectors/residential',
    '/sectors/residential-pbsa',
    '/sectors/retail-hospitality',
    '/sectors/retail-service-stations',
    '/sectors/venues',
    '/services',
    '/services/abseil-rail-certification',
    '/services/access-control',
    '/services/access-control-advanced',
    '/services/ahu-fire-interlock-testing',
    '/services/air-filtration-hepa',
    '/services/anpr-systems',
    '/services/bms-integration-testing',
    '/services/bms-optimisation',
    '/services/bmu-cradle-servicing',
    '/services/building-fabric',
    '/services/building-inspections',
    '/services/car-park-co-monitoring',
    '/services/car-park-fume-extraction',
    '/services/car-park-smoke-control',
    '/services/cctv-maintenance',
    '/services/commercial-plumbing',
    '/services/compressor-maintenance',
    '/services/critical/arc-flash-assessment',
    '/services/critical/arc-flash-assessment/birmingham',
    '/services/critical/arc-flash-assessment/chesterfield',
    '/services/critical/arc-flash-assessment/derby',
    '/services/critical/arc-flash-assessment/leeds',
    '/services/critical/arc-flash-assessment/lincoln',
    '/services/critical/arc-flash-assessment/london',
    '/services/critical/arc-flash-assessment/manchester',
    '/services/critical/arc-flash-assessment/nottingham',
    '/services/critical/arc-flash-assessment/sheffield',
    '/services/critical/data-room-audits',
    '/services/critical/data-room-audits/birmingham',
    '/services/critical/data-room-audits/chesterfield',
    '/services/critical/data-room-audits/derby',
    '/services/critical/data-room-audits/leeds',
    '/services/critical/data-room-audits/lincoln',
    '/services/critical/data-room-audits/london',
    '/services/critical/data-room-audits/manchester',
    '/services/critical/data-room-audits/nottingham',
    '/services/critical/data-room-audits/sheffield',
    '/services/critical/generator-maintenance',
    '/services/critical/generator-maintenance/birmingham',
    '/services/critical/generator-maintenance/chesterfield',
    '/services/critical/generator-maintenance/derby',
    '/services/critical/generator-maintenance/leeds',
    '/services/critical/generator-maintenance/lincoln',
    '/services/critical/generator-maintenance/london',
    '/services/critical/generator-maintenance/manchester',
    '/services/critical/generator-maintenance/nottingham',
    '/services/critical/generator-maintenance/sheffield',
    '/services/critical/hv-switching',
    '/services/critical/hv-switching/birmingham',
    '/services/critical/hv-switching/chesterfield',
    '/services/critical/hv-switching/derby',
    '/services/critical/hv-switching/leeds',
    '/services/critical/hv-switching/lincoln',
    '/services/critical/hv-switching/london',
    '/services/critical/hv-switching/manchester',
    '/services/critical/hv-switching/nottingham',
    '/services/critical/hv-switching/sheffield',
    '/services/critical/lightning-protection',
    '/services/critical/lightning-protection/birmingham',
    '/services/critical/lightning-protection/chesterfield',
    '/services/critical/lightning-protection/derby',
    '/services/critical/lightning-protection/leeds',
    '/services/critical/lightning-protection/lincoln',
    '/services/critical/lightning-protection/london',
    '/services/critical/lightning-protection/manchester',
    '/services/critical/lightning-protection/nottingham',
    '/services/critical/lightning-protection/sheffield',
    '/services/critical/lightning-protection-testing',
    '/services/critical/power-quality',
    '/services/critical/power-quality/birmingham',
    '/services/critical/power-quality/chesterfield',
    '/services/critical/power-quality/derby',
    '/services/critical/power-quality/leeds',
    '/services/critical/power-quality/lincoln',
    '/services/critical/power-quality/london',
    '/services/critical/power-quality/manchester',
    '/services/critical/power-quality/nottingham',
    '/services/critical/power-quality/sheffield',
    '/services/critical/power-redundancy',
    '/services/critical/power-redundancy/birmingham',
    '/services/critical/power-redundancy/chesterfield',
    '/services/critical/power-redundancy/derby',
    '/services/critical/power-redundancy/leeds',
    '/services/critical/power-redundancy/lincoln',
    '/services/critical/power-redundancy/london',
    '/services/critical/power-redundancy/manchester',
    '/services/critical/power-redundancy/nottingham',
    '/services/critical/power-redundancy/sheffield',
    '/services/critical/thermal-imaging',
    '/services/critical/thermal-imaging/birmingham',
    '/services/critical/thermal-imaging/chesterfield',
    '/services/critical/thermal-imaging/derby',
    '/services/critical/thermal-imaging/leeds',
    '/services/critical/thermal-imaging/lincoln',
    '/services/critical/thermal-imaging/london',
    '/services/critical/thermal-imaging/manchester',
    '/services/critical/thermal-imaging/nottingham',
    '/services/critical/thermal-imaging/sheffield',
    '/services/critical/ups-maintenance',
    '/services/critical/ups-maintenance/birmingham',
    '/services/critical/ups-maintenance/chesterfield',
    '/services/critical/ups-maintenance/derby',
    '/services/critical/ups-maintenance/leeds',
    '/services/critical/ups-maintenance/lincoln',
    '/services/critical/ups-maintenance/london',
    '/services/critical/ups-maintenance/manchester',
    '/services/critical/ups-maintenance/nottingham',
    '/services/critical/ups-maintenance/sheffield',
    '/services/critical-infrastructure',
    '/services/data-centre-cooling-compliance',
    '/services/dilapidation-compliance',
    '/services/disaster-recovery',
    '/services/dock-leveller-maintenance',
    '/services/drainage-cctv-surveys',
    '/services/drone-inspections',
    '/services/dry-riser-testing',
    '/services/electrical',
    '/services/electrical/birmingham',
    '/services/electrical/chesterfield',
    '/services/electrical/derby',
    '/services/electrical/leeds',
    '/services/electrical/lincoln',
    '/services/electrical/london',
    '/services/electrical/manchester',
    '/services/electrical/nottingham',
    '/services/electrical/sheffield',
    '/services/electrical-compliance',
    '/services/electrical-defects',
    '/services/emergency-lighting',
    '/services/emergency-lighting/birmingham',
    '/services/emergency-lighting/chesterfield',
    '/services/emergency-lighting/derby',
    '/services/emergency-lighting/leeds',
    '/services/emergency-lighting/lincoln',
    '/services/emergency-lighting/london',
    '/services/emergency-lighting/manchester',
    '/services/emergency-lighting/nottingham',
    '/services/emergency-lighting/sheffield',
    '/services/emergency-response',
    '/services/emergency-systems',
    '/services/energy-audits',
    '/services/energy-optimisation',
    '/services/energy-optimisation-advanced',
    '/services/environmental-noise-surveys',
    '/services/evacuation-chair-servicing',
    '/services/fire/birmingham',
    '/services/fire/chesterfield',
    '/services/fire/derby',
    '/services/fire/leeds',
    '/services/fire/lincoln',
    '/services/fire/london',
    '/services/fire/manchester',
    '/services/fire/nottingham',
    '/services/fire/sheffield',
    '/services/fire-alarms',
    '/services/fire-compartmentation-surveys',
    '/services/fire-safety',
    '/services/fire-suppression-systems-novec-fm200',
    '/services/front-of-house',
    '/services/fume-extraction-lev',
    '/services/gas/birmingham',
    '/services/gas/chesterfield',
    '/services/gas/derby',
    '/services/gas/leeds',
    '/services/gas/lincoln',
    '/services/gas/london',
    '/services/gas/manchester',
    '/services/gas/nottingham',
    '/services/gas/sheffield',
    '/services/gas-safety',
    '/services/general-maintenance',
    '/services/generator-maintenance',
    '/services/grease-trap-maintenance',
    '/services/hard-fm',
    '/services/hard-services',
    '/services/hard-services-fm',
    '/services/height-safety',
    '/services/hvac',
    '/services/hvac/birmingham',
    '/services/hvac/chesterfield',
    '/services/hvac/derby',
    '/services/hvac/leeds',
    '/services/hvac/lincoln',
    '/services/hvac/london',
    '/services/hvac/manchester',
    '/services/hvac/nottingham',
    '/services/hvac/sheffield',
    '/services/hvac-compliance',
    '/services/indoor-air-quality-testing',
    '/services/industrial-refrigeration',
    '/services/interceptor-maintenance',
    '/services/kitchen-suppression-systems',
    '/services/leak-detection-repair',
    '/services/lifting-equipment',
    '/services/lightning-protection-testing',
    '/services/load-bank-testing',
    '/services/loading-bay-fume-extraction',
    '/services/loading-bay-safety-systems',
    '/services/mansafe-testing',
    '/services/me-services',
    '/services/mewp-safety-checks',
    '/services/net-zero-roadmaps',
    '/services/out-of-hours-support',
    '/services/plant-room-risk-assessments',
    '/services/plumbing',
    '/services/power-quality-analysis',
    '/services/ppm',
    '/services/ppm/birmingham',
    '/services/ppm/chesterfield',
    '/services/ppm/derby',
    '/services/ppm/leeds',
    '/services/ppm/lincoln',
    '/services/ppm/london',
    '/services/ppm/manchester',
    '/services/ppm/nottingham',
    '/services/ppm/sheffield',
    '/services/pump-room-maintenance',
    '/services/pump-station-servicing',
    '/services/rising-mains',
    '/services/roller-shutter-maintenance',
    '/services/roof-safety-inspections',
    '/services/security-systems-healthcheck',
    '/services/smart-building-io-t',
    '/services/smart-metering',
    '/services/smoke-vent-systems',
    '/services/soft-fm',
    '/services/space-planning',
    '/services/sprinklers',
    '/services/stairwell-pressurisation-fans',
    '/services/sustainability-monitoring',
    '/services/thermal-imaging-surveys',
    '/services/total-facilities-management',
    '/services/ups-maintenance',
    '/services/waste-compliance',
    '/services/water/birmingham',
    '/services/water/chesterfield',
    '/services/water/derby',
    '/services/water/leeds',
    '/services/water/lincoln',
    '/services/water/london',
    '/services/water/manchester',
    '/services/water/nottingham',
    '/services/water/sheffield',
    '/services/water-hygiene',
    '/services/water-optimisation',
    '/services/water-treatment-plant-maintenance',
    '/sitemap',
    '/social-value',
    '/suppliers',
    '/sustainability',
    '/technology',
    '/tools/compliance-calendar',
    '/tools/compliance-checker',
    '/tools/fm-health-check',
    '/tools/fm-roi-calculator',
    '/tools/ppm-estimator',
    '/tools/ppm-schedule-builder',
    '/tools/tender-brief',
    '/visual-standards',
    '/why-entirefm',
    '/why-switch',
  ];

  const staticRoutes = staticRoutePaths.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'monthly' as const,
    priority: route === '' || route === '/' ? 1 : 0.8,
  }));

  // Dynamic Case Studies
  const caseStudyRoutes = caseStudies.map((cs) => ({
    url: `${baseUrl}/case-studies/${cs.slug}`,
    lastModified: new Date(),
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }));

  // Dynamic Resources
  const resourceRoutes = resources.map((ra) => ({
    url: `${baseUrl}/resources/${ra.slug}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: 0.7,
  }));

  // Dynamic Academy Courses
  const academyRoutes = academyCourses.map((course) => ({
    url: `${baseUrl}/academy/${course.slug}`,
    lastModified: new Date(),
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }));

  // Dynamic Building Walk Episodes
  const episodeRoutes = episodes.map((ep) => ({
    url: `${baseUrl}/building-walk/${ep.slug}`,
    lastModified: new Date(),
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }));

  // Dynamic Partner Types
  const partnerRoutes = partnerTypes.map((partner) => ({
    url: `${baseUrl}/partners/${partner.slug}`,
    lastModified: new Date(),
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }));

  return [
    ...staticRoutes, 
    ...caseStudyRoutes, 
    ...resourceRoutes, 
    ...academyRoutes, 
    ...episodeRoutes,
    ...partnerRoutes,
  ];
}
